name: Expo Publish

on:
  push:
    branches:
      - frontend

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use a versão Node.js compatível com o projeto

      - name: Install dependencies
        run: npm install

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD

      - name: Publish to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo publish
